stages:
  - build
  - test

variables:
  CC: cc
  CFLAGS: "-Wall -Wextra -Werror"
  LIBFT_DIR: "libft"
  BUILD_DIR: "build"

build_libft:
  stage: build
  script:
    - mkdir -p $BUILD_DIR
    - make -C $LIBFT_DIR
  artifacts:
    paths:
      - $LIBFT_DIR/libft.a

test:
  stage: test
  script:
    - mkdir -p $BUILD_DIR/tests
    - g++ $CFLAGS -I$LIBFT_DIR $LIBFT_DIR/libft.a tests/*.cpp -o $BUILD_DIR/test_libft
    - $BUILD_DIR/test_libft
  only:
    - branches
