name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../libft
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t libft-image .

    - name: Build libft
      run: |
        docker run --rm -v libft-image make -C libft

    - name: Run Tests
      run: |
        docker run --rm -v libft-image g++ -Wall -Wextra -Werror -I libft libft/libft.a tests/*.cpp -o tests/test_libft
        docker run --rm -v ./tests/test_libft
